// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtYZibXffMMpdIywDP6Pqik1OUivxdj98',
    appId: '1:859326386927:web:dae2f4f783e11bc22b411a',
    messagingSenderId: '859326386927',
    projectId: 'pawscan-3cf21',
    authDomain: 'pawscan-3cf21.firebaseapp.com',
    storageBucket: 'pawscan-3cf21.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPBwf8zmvwX16qm6EEZe16Qzq4MpIC3LE',
    appId: '1:859326386927:android:3a4ec5c19741437b2b411a',
    messagingSenderId: '859326386927',
    projectId: 'pawscan-3cf21',
    storageBucket: 'pawscan-3cf21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbIdLFu_lN_OqffIKpKWPvi4LEtKvi1WU',
    appId: '1:859326386927:ios:318e46ae6c2e3a932b411a',
    messagingSenderId: '859326386927',
    projectId: 'pawscan-3cf21',
    storageBucket: 'pawscan-3cf21.firebasestorage.app',
    iosBundleId: 'com.example.pawscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtYZibXffMMpdIywDP6Pqik1OUivxdj98',
    appId: '1:859326386927:web:7875194e302f0e1f2b411a',
    messagingSenderId: '859326386927',
    projectId: 'pawscan-3cf21',
    authDomain: 'pawscan-3cf21.firebaseapp.com',
    storageBucket: 'pawscan-3cf21.firebasestorage.app',
  );
}
